up_fork: fix the syscall error declaration error
VELAPLATFO-8890

stubs/STUB_up_fork.c: In function 'STUB_up_fork':
Error: stubs/STUB_up_fork.c:11:21: error: implicit declaration of function 'up_fork'; did you mean 'vfork'? [-Werror=implicit-function-declaration]
   11 |   return (uintptr_t)up_fork();
      |                     ^~~~~~~
      |                     vfork
cc1: all warnings being treated as errors
make[1]: *** [Makefile:70: STUB_up_fork.o] Error 1
make[1]: Target 'libstubs.a' not remade because of errors.
make: *** [tools/LibTargets.mk:149: syscall/libstubs.a] Error 2
make: Target 'all' not remade because of errors.

Signed-off-by: guoshichao <guoshichao@xiaomi.com>
Change-Id: I6e75e12ea24a6e312d92b27e767d5967a1ee4489