libc.csv: Fix macro guard for TLS related symbols
VELAPLATFO-17486

The current macro guard for TLS related symbols is
not enough, only if !defined(CONFIG_DISABLE_PTHREAD)
and CONFIG_TLS_NELEM > 0, the TLS related symbols
will enabled.

So if CONFIG_DISABLE_PTHREAD is not defined, but
TLS is disabled, the reference to TLS related symbols
will cause build error (undefined reference to xxx).

Change-Id: Ia357fbab538176b2664753990d657003fa47cbd8
Signed-off-by: Huang Qi <huangqi3@xiaomi.com>
(cherry picked from commit 580f86c37e0758c2ec27d06d856321d2aeac60e5)