cmake: add needed file to cmake script for build sim:vela
VELAPLATFO-11575

/home/zhhyu/source/matter/nuttx/crypto/chachapoly.c:232: undefined reference to `timingsafe_bcmp'

Change-Id: Ie5ce95c5c7b7d37ea3ba0e7cb52030bd8d292580
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
(cherry picked from commit 62e52864aa3be68537584e0928126eacc6261cb5)