qemu:fix ci build error when CONFIG_LIBC_FDT is not defined
VELAPLATFO-16642

when dtc code is set to be download from github, if CONFIG_LIBC_FDT is not
set, it will cause such error:
./qemu_bringup.c:33:10: fatal error: libfdt.h: No such file or directory
580   33 | #include <libfdt.h>

Change-Id: I3bcface269356acd45de2158676a87f55b7fd950
Signed-off-by: liaoao <liaoao@xiaomi.com>