spinlock: Fix misc/goldfish_pipe.c:643:3: error: implicit declaration of function 'spin_lock_init'
VELAPLATFO-30865

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
(cherry picked from commit cb81306377f6fb6ac5150f153ef75c88fb09e7a9)